alt_email can be nil, use blank? instead of empty?
> [12] pry(main)> nil.blank?
> => true
> [13] pry(main)> nil.empty?
> NoMethodError: undefined method `empty?' for nil:NilClass
> from (pry):13:in `__pry__'